#!/usr/bin/env bash
# Regenerate the gh-pages landing index.html listing main/ and every active pr-*/ preview.
#
# Usage: regen-landing.sh <gh-pages-checkout-dir>

set -euo pipefail

site_dir="${1:?usage: regen-landing.sh <gh-pages-checkout-dir>}"
cd "$site_dir"

index="index.html"
now="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"

rows=""

if [ -d main ]; then
    rows+="    <li><a href=\"main/\"><strong>main</strong></a> &mdash; latest build of the default branch</li>\n"
fi

# Collect PR previews, newest first by directory mtime.
if compgen -G 'pr-*' >/dev/null; then
    while IFS= read -r pr_dir; do
        pr_num="${pr_dir#pr-}"
        # Pick the most recently modified commit subdirectory.
        latest_sha_dir=$(find "$pr_dir" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %f\n' 2>/dev/null \
            | sort -rn | head -1 | awk '{print $2}')
        if [ -n "$latest_sha_dir" ]; then
            short_sha="${latest_sha_dir:0:7}"
            rows+="    <li><a href=\"${pr_dir}/${latest_sha_dir}/\">PR #${pr_num}</a> &mdash; latest commit <code>${short_sha}</code></li>\n"
        else
            rows+="    <li><a href=\"${pr_dir}/\">PR #${pr_num}</a></li>\n"
        fi
    done < <(find . -maxdepth 1 -type d -name 'pr-*' -printf '%f\n' | sort -t- -k2 -n -r)
fi

if [ -z "$rows" ]; then
    rows="    <li><em>No builds published yet.</em></li>"
fi

cat >"$index" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>compute-board &mdash; CI previews</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root { color-scheme: light dark; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           max-width: 720px; margin: 3rem auto; padding: 0 1.25rem; line-height: 1.55; }
    h1 { margin-bottom: 0.25rem; }
    .sub { color: #666; margin-top: 0; }
    ul { padding-left: 1.25rem; }
    li { margin: 0.35rem 0; }
    footer { margin-top: 3rem; font-size: 0.85rem; color: #888; }
    code { background: rgba(128,128,128,0.15); padding: 0.1rem 0.35rem; border-radius: 3px; }
  </style>
</head>
<body>
  <h1>compute-board</h1>
  <p class="sub">KiCad CI previews &mdash; generated by GitHub Actions</p>
  <h2>Available builds</h2>
  <ul>
$(printf '%b' "$rows")
  </ul>
  <footer>
    Regenerated at ${now}.
    Source: <a href="https://github.com/jescarri/compute-board">jescarri/compute-board</a>.
  </footer>
</body>
</html>
HTML

echo "Wrote ${site_dir}/${index}"
