#!/usr/bin/env bash
# Replace the block between <!-- KICAD_CI:START --> and <!-- KICAD_CI:END -->
# in README.md with a freshly-generated snippet pointing at the main-branch
# GitHub Pages preview.
#
# Required env:
#   SITE_URL     e.g. https://jescarri.github.io/compute-board/main
#   COMMIT_SHA   full sha of the commit that triggered the build

set -euo pipefail

readme="${README_PATH:-README.md}"
site_url="${SITE_URL:?SITE_URL must be set}"
commit_sha="${COMMIT_SHA:?COMMIT_SHA must be set}"
short_sha="${commit_sha:0:7}"
now="$(date -u +'%Y-%m-%d')"

start_marker='<!-- KICAD_CI:START - Do not edit; auto-generated by .github/workflows/kicad-ci.yml -->'
end_marker='<!-- KICAD_CI:END -->'

if [ ! -f "$readme" ]; then
    echo "::error::README file not found at $readme" >&2
    exit 1
fi

if ! grep -qF "$start_marker" "$readme" || ! grep -qF "$end_marker" "$readme"; then
    echo "::error::README is missing the KICAD_CI markers" >&2
    exit 1
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# shellcheck disable=SC2016
cat >"$tmp" <<MARKDOWN
${start_marker}
[![ERC](https://img.shields.io/endpoint?url=${site_url}/badges/erc.json)](${site_url}/)
[![DRC](https://img.shields.io/endpoint?url=${site_url}/badges/drc.json)](${site_url}/)

### Board preview

| Top | Bottom |
|---|---|
| ![top](${site_url}/3d/top.png) | ![bottom](${site_url}/3d/bottom.png) |

- [Schematic (PDF)](${site_url}/schematic/)
- [PCB layers (PDF)](${site_url}/pcb/)
- [STEP file](${site_url}/)
- [Full preview site](${site_url}/)

_Last updated from commit \`${short_sha}\` on ${now}._
${end_marker}
MARKDOWN

# Replace the block in-place using awk so we stay portable (no GNU-only sed flags).
awk -v start="$start_marker" -v end="$end_marker" -v block_file="$tmp" '
    BEGIN { in_block = 0 }
    index($0, start) == 1 {
        while ((getline line < block_file) > 0) print line
        close(block_file)
        in_block = 1
        next
    }
    in_block == 1 {
        if (index($0, end) == 1) { in_block = 0 }
        next
    }
    { print }
' "$readme" >"${readme}.new"

mv "${readme}.new" "$readme"
echo "Updated $readme"
